name: Deploy Next.js App to Krystal Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    # Step 3: Build the project
    - name: Build the project
      run: npm run build

    - name: Create deployment directory
      run: mkdir -p deployment

    # Step 3: Zip the .next directory and place it in the deployment folder
    - name: Zip .next directory
      run: zip -r deployment/next.zip .next/

    - name: Upload compressed .next directory
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./deployment/
        server-dir: /deployment/
        exclude: |
          .git/
          .git/**
          .next/cache/**
          node_modules/**
          .github/**
      
    # Step 2: Upload the 'app' directory
    - name: Upload app directory
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./app/
        server-dir: /app/
        exclude: |
          .git/
          .git/**
          .next/cache/**
          node_modules/**
          .github/**

    # Step 3: Upload the 'components' directory
    - name: Upload components directory
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./components/
        server-dir: /components/
        exclude: |
          .git/
          .git/**
          .next/cache/**
          node_modules/**
          .github/**

    # Step 4: Upload the remaining files and directories
    - name: Upload remaining files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./
        server-dir: /
        exclude: |
          .git/
          .git/**
          .next/**
          node_modules/**
          .github/**
          public/**
          app/**
          components/**
          
    # Step 5: Retry logic for failed uploads
    - name: Retry failed uploads
      run: |
        echo "Implement retry logic here if needed. You can use a different tool or script to handle retries."

    # Step 6: Notify on failure
    - name: Notify on failure
      if: failure()
      run: |
        echo "Deployment failed. Please check the logs for details."
        # You can add additional notification steps here (e.g., send an email or Slack message).
