name: Deploy Next.js App to Krystal Hosting

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Krystal Hosting via FTPS
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.wecarhire.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps 
        local-dir: ./
        server-dir: /home/wecarhir/test06.aldortech.com/  # Adjust this if your app is in a different directory
        exclude: |
          .git/
          .next/cache/
          node_modules/
          .github/ 
