name: Deploy Next.js App to Krystal Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Step 1: Upload the 'public' folder
    - name: Upload public folder
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./public/
        server-dir: /
        exclude: |
          .git/
          .git/**
          .next/cache/**
          node_modules/**
          .github/**

    # Step 2: Upload the 'app' directory
    - name: Upload app directory
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./app/
        server-dir: /
        exclude: |
          .git/
          .git/**
          .next/cache/**
          node_modules/**
          .github/**

    # Step 3: Upload the 'components' directory
    - name: Upload components directory
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./components/
        server-dir: /
        exclude: |
          .git/
          .git/**
          .next/cache/**
          node_modules/**
          .github/**

    # Step 4: Upload the remaining files and directories
    - name: Upload remaining files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./
        server-dir: /
        exclude: |
          .git/
          .git/**
          .next/cache/**
          node_modules/**
          .github/**
          public/**
          app/**
          components/**
